language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - ./build/linux/build.sh

deploy:
  provider: "heroku"
    api_key: "952e3585-e86e-4f83-885e-77e82c839710"
    app: "jf-jdjobs-dev"
  on:
    all_branches: true